provider "aws" {
  region  = "${var.aws_region}"
  version = "~> 0.1"
}

/* global settings for customization */
variable "project_name" {
  description = "Project Name (should be 5-10 lowercase chars). Must be unique between projects for AWS"
  default     = "magecloudkit"
}

variable "internal_domain" {
  description = "Internal domain. !!! If you change this value be sure to do a global search and replace. !!!"
  default     = "magecloudkit.internal"
}

variable "ecs_ami" {
  description = "Host AMI for ECS Containers, Generated by Packer"
  default     = "ami-72a1df08"
}

variable "app_server_count" {
  default = {
    production = "4"
    staging    = "4"
    qa         = "4"
  }
}

// desired number of ECS tasks to run for the application
// when doing a rolling ASG deployment you should increase
// this number to (2 * app_server_count) and return it to
// its original value after Terraform has finished
variable "app_task_count" {
  default = {
    production = "2"
    staging    = "2"
    qa         = "8"
  }
}

variable "rds_password" {
  description = "RDS password"

  default = {
    production = "aekeeneijeTh1CaeKee6aing7woh8eiv"
    staging    = "Yo8thai0sesee1co6theighahmue5Eth"
    qa         = "Ooraihi7ahBopis3oothooZei5pawaim"
  }
}
