#!/bin/bash

set -e

echo "Installing PHP 7.0..."

LC_ALL="en_US.UTF-8"
sudo DEBIAN_FRONTEND=noninteractive apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y php7.0-cli \
  php7.0-bcmath \
  php7.0-gd \
  php7.0-intl \
  php7.0-mbstring \
  php7.0-mcrypt \
  php7.0-mysql \
  php7.0-opcache \
  php7.0-soap \
  php7.0-xsl \
  php7.0-zip
