# ---------------------------------------------------------------------------------------------------------------------
# REQUIRED PARAMETERS
# You must provide a value for each of these parameters.
# ---------------------------------------------------------------------------------------------------------------------

variable "name" {
  description = "The name used for the EFS resources"
  default     = ""
}

variable "vpc_id" {
  description = " The VPC ID where the resources will be deployed."
}

variable "availability_zones" {
  description = "List of availability zones"
  type        = "list"
}

variable "subnet_ids" {
  description = "The IDs of the Subnets in which to launch the EFS resources"
  type        = "list"
}

# ---------------------------------------------------------------------------------------------------------------------
# OPTIONAL PARAMETERS
# These parameters are preconfigured and have reasonable default values.
# ---------------------------------------------------------------------------------------------------------------------

variable "creation_token" {
  description = "A unique name up to 64 characters used as reference when creating the Elastic File System to ensure idempotent file system creation. If blank, then the value is automatically generated by Terraform."
  default     = ""
}

variable "encrypted" {
  description = "Whether or not to encrypt the file system contents."
  default     = false
}

variable "kms_key_id" {
  description = "The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true."
  default     = ""
}

variable "performance_mode" {
  description = "The file system performance mode. Can be either 'generalPurpose' or 'maxIO'. Defaults to 'generalPurpose'."
  default     = "generalPurpose"
}

variable "throughput_mode" {
  description = "Throughput mode for the file system. Defaults to 'bursting'. Valid values: 'bursting' or 'provisioned'. When using 'provisioned', also set provisioned_throughput_in_mibps."
  default     = "bursting"
}

variable "provisioned_throughput_in_mibps" {
  description = "The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with throughput_mode set to provisioned."
  default     = 0
}

variable "allowed_inbound_from_cidr_blocks" {
  description = "A list of CIDR-formatted IP address ranges from which the EFS resources will allow NFS connections."
  type        = "list"
  default     = []
}

variable "allowed_inbound_security_group_ids" {
  description = "A list of Security Group IDs from which the EFS resources will allow incoming NFS connections."
  type        = "list"
  default     = []
}

variable "efs_port" {
  description = "The port used for EFS NFS connections"
  default     = 2049
}

variable "tags" {
  description = "A map of extra tag blocks added to the resources. Each element in this map is a key/value pair mapped to the respective values."
  type        = "map"
  default     = {}

  # Example:
  #
  # default = {
  #   key = "value"
  # }
}
